# Generated by Django 4.1.1 on 2022-10-13 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('adress', models.CharField(max_length=150)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('academic_year', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=150)),
                ('adress', models.CharField(max_length=150)),
                ('number', models.IntegerField()),
                ('student_number', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('isvalidated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('nom', models.CharField(max_length=150)),
                ('adress', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=150)),
                ('salaire', models.FloatField()),
                ('formateur_number', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('nom', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('prix', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('Formateur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.formateur')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('capacite', models.IntegerField()),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=100)),
                ('isvalidated', models.BooleanField(default=False)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.formation')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='formation',
            name='salle',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.salle'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='formation',
            field=models.ManyToManyField(to='accounts.formation'),
        ),
    ]
