# Generated by Django 4.1.1 on 2022-10-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='academic_year',
        ),
    ]
